services:
  postgres:
    image: postgres:16
    container_name: jump-advisor-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jump_advisor
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 